// joint.ts first: the model modules form an import cycle that only
// initializes cleanly when entered here (see test-utils/verification/fixture.ts).
import '../../app/model/joint';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  LIBRARY_TEMPLATE_IDS,
  TEMPLATE_IDS,
  TEMPLATE_LINKAGES,
} from '../../app/component/MODALS/templates/template-linkages';
import { fixturePayload } from '../../test-utils/verification/fixture-gallery';
import {
  FORCE_STUDY_TEMPLATES,
  libraryTemplateEntry,
  libraryTemplateMasses,
} from '../../test-utils/verification/template-fixtures';
import { buildMechanism } from '../../test-utils/verification/fixture';
import { PrisJoint } from '../../app/model/joint';
import { libraryTemplateFills, logicalFills } from '../../test-utils/verification/template-colors';
import { urlGeneratorFor } from '../../test-utils/url-encoding';
import { RealLink } from '../../app/model/link';
import { StringTranscoder } from '../../app/services/transcoding/string-transcoder';
import { buildMechanismFixture } from '../fixtures/mechanism-fixtures';
import { partitionMechanisms } from '../../app/model/mechanism/mechanism-partition';
import { Mechanism } from '../../app/model/mechanism/mechanism';

/** Any non-zero input: this asks whether a machine solves, not how fast. */
const SOLVED_INPUT_ANG_VEL = (10 * Math.PI) / 30;

// The library templates are generated, not typed in. A template and the fixture
// a spec asserts on are the same mechanism, and this is what keeps them that
// way: encode the fixture, compare against what is checked in, and fail with
// the command that fixes it. Same contract as docs/fixture-urls.md.
//
// Run `npm run template-payloads` to regenerate.

const SOURCE_PATH = resolve(__dirname, '../../app/component/MODALS/templates/template-linkages.ts');
const START = '  // <generated by `npm run template-payloads` — do not edit by hand>';
const END = '  // </generated>';

/** The generated block, formatted the way Prettier leaves it in the source. */
function generatedBlock(): string {
  const entries = LIBRARY_TEMPLATE_IDS.map((id) => {
    const entry = libraryTemplateEntry(id);
    // The same payload the published gallery links to, drawing scale included:
    // the card and the doc row are the same picture of the same mechanism.
    // Mass is the one thing the library decides for itself — a doc link opens
    // the mechanism a spec asserts on, and a template opens a lesson.
    const payload = fixturePayload(
      entry.fixture,
      entry.objectScale,
      entry.speed,
      libraryTemplateMasses(id),
      // Color is the other thing the library decides for itself: a gallery
      // link is a mechanism to check, a template is a mechanism to read.
      libraryTemplateFills(id, entry.fixture)
    );
    return `  ${id}:\n    '${payload}',`;
  });
  return [START, ...entries, END].join('\n');
}

function replaceBlock(source: string, block: string): string {
  const from = source.indexOf(START);
  const to = source.indexOf(END);
  if (from < 0 || to < 0) throw new Error('template-linkages.ts has lost its generated markers');
  return source.slice(0, from) + block + source.slice(to + END.length);
}

/**
 * The six templates that predate the generator, kept to the same color rule.
 *
 * Their geometry is hand-authored and stays that way — there is no fixture to
 * regenerate them from. But color is not geometry, and six cards colored by
 * whatever order somebody drew them in, sitting in a dialog beside thirty-four
 * colored from their structure, is the inconsistency this rule exists to
 * remove. So the payload is decoded, repainted and re-encoded.
 *
 * That round trip used to come back byte-identical but for the six color
 * fields, and that was what made it safe to do to a string nothing else can
 * regenerate. Since Stage 1 it also *normalizes* a slider: a payload spelling
 * one as three objects is folded on the way in and written back as the single
 * joint, which is why `Slider_Crank` changed shape here the first time this
 * ran after the fold landed. That much is wanted — the dialog should hand out
 * what the app writes today — and `transcoding/url-slider-fold.spec.ts` is
 * what proves the fold loses nothing. Anything *else* coming back different
 * is a bug in the codec, not a repaint.
 */
const HAND_AUTHORED = [
  '4-Bar',
  'Watt_I',
  'Watt_II',
  'Stephenson_III',
  'Slider_Crank',
  'Locked_Four_Bar',
] as const;

function recolored(id: string, payload: string): string {
  const { service, settings } = buildMechanismFixture(payload);
  // Only the drawn bodies, which is also what narrows the type. A slider used
  // to put a `Link` that is not a `RealLink` in here, drawn black rather than
  // in one of the six; it is one joint now and brings no body of its own.
  const bodies = service.links.filter((link): link is RealLink => link instanceof RealLink);
  const grounds = new Set(
    service.joints
      .filter((joint) => (joint as { ground?: boolean }).ground)
      .map((joint) => joint.id)
  );
  const fills = logicalFills(
    bodies.map((link) => ({ id: link.id, jointIds: link.joints.map((joint) => joint.id) })),
    grounds,
    {},
    id
  );
  bodies.forEach((link) => {
    const color = fills.get(link.id);
    if (color) link.fill = color;
  });
  return urlGeneratorFor(service, settings).generateUrlQuery();
}

/**
 * Everything a payload says except what color it says it in.
 *
 * `recolored` is allowed to change the six fill fields and nothing else, and
 * `Slider_Crank` proved how easy that is to miss: the fold changed its shape
 * the first time the generator ran after it landed, and the only thing that
 * announced it was a reviewer reading the diff. Decoded rather than diffed as
 * text, because a codec change is exactly the case this has to catch and a
 * codec change moves every byte.
 */
function contentDigest(payload: string): string {
  const decoder = new StringTranscoder();
  decoder.decodeURL(payload);
  return JSON.stringify({
    joints: decoder.getJoints(),
    links: decoder.getLinks().map(({ color: _color, ...rest }) => rest),
    forces: decoder.getForces(),
  });
}

function replaceHandAuthored(source: string, announce: boolean): string {
  return HAND_AUTHORED.reduce((text, id) => {
    // The key is quoted only when it is not a bare identifier ('4-Bar' is not).
    const row = new RegExp(`^( {2}'?${id}'?:\\n {4}')([^']+)(',)$`, 'm');
    const found = text.match(row);
    if (!found) throw new Error(`template-linkages.ts has lost its ${id} row`);
    const rewritten = recolored(id, found[2]);
    // These six have no fixture to regenerate them from, so a rewrite here is
    // the only copy of that mechanism changing. Said out loud on the way past:
    // the read path's fixed-point check below is a real guard, but the write
    // path a developer actually runs had nothing to say, so the next codec
    // change would rewrite all six as silently as this one did.
    if (announce && contentDigest(rewritten) !== contentDigest(found[2])) {
      console.warn(
        `template-payloads: ${id} changed beyond its colors — check the diff before committing.`
      );
    }
    return text.replace(row, `$1${rewritten.replace(/\\/g, '\\\\')}$3`);
  }, source);
}

describe('library template payloads', () => {
  it('match what their verification fixtures encode to', () => {
    const source = readFileSync(SOURCE_PATH, 'utf8');
    const writing = !!process.env['PMKS_WRITE_TEMPLATE_PAYLOADS'];
    const regenerated = replaceHandAuthored(replaceBlock(source, generatedBlock()), writing);
    if (writing) {
      writeFileSync(SOURCE_PATH, regenerated);
      return;
    }
    expect(source, 'run `npm run template-payloads`').toBe(regenerated);
  });
});

describe('the five force studies the library publishes', () => {
  // `scaleLoading` walks what a mechanism is made of and multiplies its weight,
  // and a slider's weight moved from a zero-length block link onto the joint in
  // Stage 1 of `docs/joint-type-and-cylinder-plan.md`. Walking `links` alone
  // after that left Punch_Press with a 6 kg ram beside a 200 kg crank and a
  // 300 kg rod, in the one template whose comment explains that these masses
  // were scaled so Static and In-motion stop reporting the same number -- and
  // nothing said so, because this file compares the payload against what the
  // same helper generates. So the scaling is asserted here rather than only
  // being applied.
  for (const id of FORCE_STUDY_TEMPLATES) {
    it(`${id} scales every massive part, sliders included`, () => {
      const { service } = buildMechanismFixture(TEMPLATE_LINKAGES[id]);
      const entry = libraryTemplateEntry(id);
      const source = buildMechanism(entry.fixture);
      const scale = (libraryTemplateMasses(id) as { mass: number }).mass;

      const wanted = new Map<string, number>();
      source.links.forEach((link) => wanted.set(`link:${link.id}`, link.mass * scale));
      source.joints.forEach((joint) => {
        if (joint instanceof PrisJoint) wanted.set(`joint:${joint.id}`, joint.mass * scale);
      });

      const got = new Map<string, number>();
      service.links.forEach((link) => got.set(`link:${link.id}`, link.mass));
      service.joints.forEach((joint) => {
        if (joint instanceof PrisJoint) got.set(`joint:${joint.id}`, joint.mass);
      });

      for (const [part, mass] of wanted) {
        expect(got.get(part), `${id} ${part}`).toBeCloseTo(mass, 6);
      }
    });
  }
});

describe('every template the library dialog offers', () => {
  for (const id of TEMPLATE_IDS) {
    describe(id, () => {
      it('decodes without throwing', () => {
        const decoder = new StringTranscoder();
        expect(() => decoder.decodeURL(TEMPLATE_LINKAGES[id])).not.toThrow();
        expect(decoder.getJoints().length).toBeGreaterThan(1);
      });

      it('opens as machines the user can play, every one of them', () => {
        // A template that opens to a mechanism the user cannot play is worse
        // than no template: the dialog promises a working example.
        //
        // Asked of each machine rather than of the drawing, because a drawing
        // may hold several. Three independent four-bars are three one-DoF
        // machines and a three-DoF document, and it is the machines the reader
        // presses play on.
        const { service } = buildMechanismFixture(TEMPLATE_LINKAGES[id]);
        const partitioning = partitionMechanisms(service.joints, service.links, service.forces);
        expect(partitioning.mechanisms.length).toBeGreaterThan(0);
        expect(partitioning.unassigned.looseJoints.length).toBe(0);

        partitioning.mechanisms.forEach((partition) => {
          const machine = new Mechanism(
            partition.joints,
            partition.links,
            partition.forces,
            [],
            true,
            'cm',
            SOLVED_INPUT_ANG_VEL,
            'adaptive',
            new Set(partition.ownJoints.map((joint: { id: string }) => joint.id))
          );
          expect(machine.dof).toBe(1);
          expect(machine.isMechanismValid()).toBe(true);
          expect(machine.joints.length).toBeGreaterThan(20);
        });
      });
    });
  }
});
